/*
 * generated by Xtext 2.14.0
 */
package compilateur.nasm


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class NasmStandaloneSetup extends NasmStandaloneSetupGenerated {

	def static void doSetup() {
		new NasmStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
