/*
 * generated by Xtext 2.14.0
 */
package compilateur.nasm


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class NasmRuntimeModule extends AbstractNasmRuntimeModule {
}
